# Site settings
title: Paper Survey
email: mesitahiro@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Listing memo of reading paper in japanese
baseurl: "/paper-survey" # the subpath of your site, e.g. /newpath-for-emping
url: "https://meshidenn.github.io/" # the base hostname & protocol for your site
twitter_username: meshidenn
github_username:  meshidenn
GoogleAnalytics: UA-xxxxxx-x

twitter:
  username: meshidenn
sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/summary/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/summary/:num'
